version: "2"

services:
  worker:
    image: ijm-worker:latest
    container_name: wangrat-ijm-worker
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp=unconfined
    environment:
      DATABASE_URL: postgresql://postgres:postgres@matemagician.deib.polimi.it:5433/ijm
      HOST_ROOT: /host
      HOST_PROJECT_ROOT: /home/wangrat/ijm
      NODE_ID: ${NODE_ID}
      DOCKER_HOST: unix:///docker.sock
    volumes:
      - ${DOCKER_SOCK}:/docker.sock
      - .:/host
