version: "2"

services:
  postgres:
    image: postgres:16
    container_name: wangrat-ijm-postgres
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    environment:
      POSTGRES_DB: ijm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ../data/pg:/var/lib/postgresql

  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile.server
    container_name: wangrat-ijm-worker
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ijm
      HOST_ROOT: /host
      HOST_PROJECT_ROOT: /home/wangrat/ijm
      NODE_ID: matemagician
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/host
