#!/usr/bin/env python3
"""Generate the drift-reconcile TikZ chart from a fault-injection slot timeseries.

Reads ``slots_timeline.csv`` (produced by
``documentation/report/e2e_runs/fault_injection/run.py``) and emits a small
hand-rolled TikZ step plot to ``Files/chart_faults.tex`` — used_db (solid, the
authority) vs used_mem (dashed, the follower), with the drift windows shaded and
the reconcile deltas annotated.  No pgfplots: mirrors the in-repo TikZ charting
approach of ``generate_chart_tex.py`` so every report figure stays
auto-generated from a committed log.

Usage:
    python infra/generate_fault_chart.py \
        [documentation/report/e2e_runs/fault_injection/slots_timeline.csv] \
        [documentation/report/Files/chart_faults.tex]
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_CSV = REPO / "documentation/report/e2e_runs/fault_injection/slots_timeline.csv"
DEFAULT_OUT = REPO / "documentation/report/Files/chart_faults.tex"

XS = 0.62  # cm per second
YS = 1.25  # cm per GPU level


def _changepoints(rows: list[dict], key: str) -> list[tuple[float, int]]:
    """(t, value) only where ``value`` changes — the step corners."""
    pts: list[tuple[float, int]] = []
    last: int | None = None
    for r in rows:
        v = int(r[key])
        if v != last:
            pts.append((float(r["t"]), v))
            last = v
    return pts


def _step_path(pts: list[tuple[float, int]], t_end: float) -> str:
    """TikZ coordinate chain for a left-continuous step function."""
    coords: list[str] = []
    for i, (t, v) in enumerate(pts):
        coords.append(f"({t:.2f},{v})")
        nxt = pts[i + 1][0] if i + 1 < len(pts) else t_end
        coords.append(f"({nxt:.2f},{v})")  # hold the level to the next corner
    return " -- ".join(coords)


def _drift_intervals(rows: list[dict]) -> list[tuple[float, float]]:
    """Contiguous windows where drift=true → (start_t, reconcile_t)."""
    intervals: list[tuple[float, float]] = []
    start: float | None = None
    for r in rows:
        is_drift = r["drift"].strip().lower() == "true"
        if is_drift and start is None:
            start = float(r["t"])
        elif not is_drift and start is not None:
            intervals.append((start, float(r["t"])))
            start = None
    return intervals


def main() -> int:
    csv_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT

    with open(csv_path) as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise SystemExit(f"no rows in {csv_path}")

    t_end = float(rows[-1]["t"])
    db_pts = _changepoints(rows, "used_db")
    mem_pts = _changepoints(rows, "used_mem")
    bands = _drift_intervals(rows)

    lines: list[str] = []
    lines.append("% Auto-generated by infra/generate_fault_chart.py — do not edit by hand.")
    lines.append(f"% Source: {csv_path.relative_to(REPO)}")
    lines.append(
        f"\\begin{{tikzpicture}}[x={XS}cm, y={YS}cm, font=\\footnotesize,\n"
        "    dbline/.style={draw=blue!60!black, line width=1.1pt},\n"
        "    memline/.style={draw=orange!85!black, line width=1.1pt, dash pattern=on 3pt off 2pt},\n"
        "    driftband/.style={fill=black!8, draw=none},\n"
        "    delta/.style={font=\\scriptsize, text=black!70},\n"
        "  ]"
    )

    # Drift bands (behind everything).
    for a, b in bands:
        lines.append(f"  \\fill[driftband] ({a:.2f},0) rectangle ({b:.2f},2.35);")

    # Axes.
    lines.append(f"  \\draw[->] (0,0) -- ({t_end + 1.5:.2f},0);")
    lines.append(f"  \\node[anchor=west, font=\\scriptsize] at ({t_end + 1.5:.2f},0) {{time [s]}};")
    lines.append("  \\draw[->] (0,0) -- (0,2.5);")
    for y in (0, 1, 2):
        lines.append(f"  \\draw (0,{y}) -- (-0.3,{y}) node[anchor=east, font=\\scriptsize] {{{y}}};")
    lines.append("  \\node[anchor=south, rotate=90, font=\\scriptsize] at (-1.1,1.25) {GPUs in use};")
    for x in range(0, int(t_end) + 1, 5):
        lines.append(f"  \\draw[black!30] ({x},0) -- ({x},-0.08) node[anchor=north, font=\\scriptsize, text=black] {{{x}}};")

    # Step lines: db (authority) solid, mem (follower) dashed.
    lines.append(f"  \\draw[dbline] {_step_path(db_pts, t_end)};")
    lines.append(f"  \\draw[memline] {_step_path(mem_pts, t_end)};")

    # Reconcile-delta annotations: where mem changes to meet db.
    for i in range(1, len(mem_pts)):
        t, v = mem_pts[i]
        prev = mem_pts[i - 1][1]
        d = v - prev
        sign = f"$+{d}$" if d > 0 else f"$-{abs(d)}$"
        lines.append(f"  \\node[delta, anchor=south] at ({t:.2f},{max(v, prev) + 0.12:.2f}) {{{sign}}};")

    # Phase B / C labels positioned over their injection windows.
    if bands:
        lines.append(f"  \\node[font=\\footnotesize\\bfseries, text=black!75] at ({bands[0][0] + 2.0:.2f},2.62) {{B: missed-acquire}};")
        lines.append(f"  \\node[font=\\footnotesize\\bfseries, text=black!75] at ({bands[-1][0] + 0.6:.2f},2.62) {{C: dropped {{\\scriptsize NOTIFY}}}};")

    # Legend.
    lines.append("  \\begin{scope}[shift={(0,-1.15)}, x=1cm, y=0.45cm]")
    lines.append("    \\draw[dbline] (0,0.3) -- (0.9,0.3);")
    lines.append("    \\node[anchor=west, font=\\scriptsize] at (1.0,0.3) {used\\_db (DB authority)};")
    lines.append("    \\draw[memline] (5.2,0.3) -- (6.1,0.3);")
    lines.append("    \\node[anchor=west, font=\\scriptsize] at (6.2,0.3) {used\\_mem (semaphore)};")
    lines.append("    \\fill[driftband] (10.4,0.05) rectangle (10.9,0.55);")
    lines.append("    \\node[anchor=west, font=\\scriptsize] at (11.0,0.3) {drift window};")
    lines.append("  \\end{scope}")

    lines.append("\\end{tikzpicture}")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({len(db_pts)} db corners, {len(mem_pts)} mem corners, {len(bands)} drift bands)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
