#!/usr/bin/env python3
"""Generate a LaTeX/TikZ Gantt chart from a run snapshot.

Mirrors :mod:`generate_chart` (matplotlib PNG) but emits a self-contained
``\\begin{tikzpicture}...\\end{tikzpicture}`` block intended to be
``\\input``'d from the report.  Coordinates are deterministic: every bar
position comes from segments derived from ``api.log`` and
``worker_*.log``, the same data the PNG generator uses.  No hand-tuned
numbers, no chance of oversubscription that the underlying data does
not actually contain.

Usage::

    python infra/generate_chart_tex.py <snapshot_dir> <out.tex> \
        [--label <jid_prefix>=<display_name>] [--label ...]

The ``--label`` flag maps a job id prefix (any unique prefix, typically
the 8-char one used in chart_s1.png) to a display name shown on the
row.  Unmapped jobs fall back to ``J1``, ``J2``, ... by submission order
(matching :mod:`generate_chart`).
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

# Reuse the PNG generator's parsing helpers so the two charts stay in sync.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_chart import (  # noqa: E402
    derive_segments,
    parse_log,
    parse_progress,
    parse_worker_log,
)
import json  # noqa: E402
import re  # noqa: E402
from datetime import timedelta  # noqa: E402


def _parse_iso(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00")).astimezone().replace(tzinfo=None)


_SUBMIT_LINE = re.compile(
    r"^(\d{2}:\d{2}:\d{2}\.\d+)\s+\S+\s+\S+:\s+.*?\b([0-9a-f]{8})\b"
)


def _parse_submit_times(api_log: Path, anchor_day: datetime) -> dict[str, datetime]:
    """First appearance per 8-char job id in api.log = real submit time.

    The scheduler emits ``Scheduling job <jid> (type=...)`` immediately
    upon submission, which beats the matched ``Scheduled job`` /
    ``Optimizer assigned`` / ``Remote run`` lines the segment derivation
    relies on.  Using this anchor (rather than ``jobs.json.created_at``,
    which is a placeholder in fixture snapshots) gives realistic queue
    durations for late-arriving jobs like URGENT.
    """
    from generate_chart import parse_time  # noqa: PLC0415

    out: dict[str, datetime] = {}
    if not api_log.exists():
        return out
    for raw in api_log.read_text(errors="replace").splitlines():
        m = _SUBMIT_LINE.match(raw)
        if not m:
            continue
        ts_s, jid = m.group(1), m.group(2)
        if jid in out:
            continue
        out[jid] = parse_time(ts_s, anchor_day)
    return out


def _load(snap_dir: Path) -> tuple[list, dict, dict, datetime]:
    """Replicate ``generate_chart.make_chart`` up to (segments, jobs, progress, t0)."""
    jobs = json.loads((snap_dir / "jobs.json").read_text())
    sc = (snap_dir / "scenario.log").read_text() if (snap_dir / "scenario.log").exists() else ""
    first_t = re.search(r"\[(\d{2}:\d{2}:\d{2})\]", sc)
    anchor_day = datetime.now().replace(microsecond=0)
    if first_t:
        h, m, s = map(int, first_t.group(1).split(":"))
        anchor_day = anchor_day.replace(hour=h, minute=m, second=s)
    events = parse_log(snap_dir / "api.log", anchor_day)
    if not events:
        raise SystemExit("No events parsed from api.log")
    api_first = min(e["ts"] for e in events)
    api_last = max(e["ts"] for e in events)
    window_end = api_last + timedelta(hours=4)
    for worker_log in snap_dir.glob("worker_*.log"):
        for ev in parse_worker_log(worker_log, anchor_day):
            if api_first <= ev["ts"] <= window_end:
                events.append(ev)
    events.sort(key=lambda e: e["ts"])
    segs = derive_segments(events, jobs)
    progress = parse_progress(snap_dir / "jobs")
    submit_ts = _parse_submit_times(snap_dir / "api.log", anchor_day)
    current_jids = {j["id"][:8] for j in jobs}
    t0 = min(
        (ev["ts"] for ev in events if ev["kind"] == "dispatch" and ev.get("jid") in current_jids),
        default=anchor_day,
    )
    return events, jobs, {"segs": segs, "progress": progress, "submit_ts": submit_ts}, t0


# ---------------------------------------------------------------------------
# TikZ emission

PREAMBLE = r"""% Auto-generated by infra/generate_chart_tex.py — do not edit by hand.
% Source snapshot: {snap}
\begin{{tikzpicture}}[x={xscale}cm, y=0.75cm, font=\footnotesize,
    nodeA40/.style={{draw=blue!60!black, fill=blue!22, line width=0.4pt}},
    nodeP600/.style={{draw=red!60!black,  fill=red!22,  line width=0.4pt}},
    profhatchA/.style={{pattern=north east lines, pattern color=blue!60!black}},
    profhatchP/.style={{pattern=north east lines, pattern color=red!60!black}},
    queued/.style={{dotted, gray!70, line width=0.6pt}},
    deadlinev/.style={{dashed, violet!70!black, line width=0.7pt}},
  ]
"""

POSTAMBLE = r"""  % Two-row legend below the chart.
  \begin{{scope}}[shift={{(0,{legend_y1})}}, x=1.0cm, y=0.45cm]
    \draw[nodeA40] (0,0) rectangle (0.6,0.6);
    \node[anchor=west] at (0.65,0.3) {{\scriptsize polimi-gpu (A40)}};
    \draw[nodeP600] (3.0,0) rectangle (3.6,0.6);
    \node[anchor=west] at (3.65,0.3) {{\scriptsize matemagician (P600)}};
    \draw[nodeA40] (6.6,0) rectangle (7.2,0.6);
    \draw[profhatchA] (6.6,0) rectangle (7.2,0.6);
    \node[anchor=west] at (7.25,0.3) {{\scriptsize hatched $=$ profile (taller $=$ 2-GPU)}};
  \end{{scope}}
  \begin{{scope}}[shift={{(0,{legend_y2})}}, x=1.0cm, y=0.45cm]
    \draw[queued] (0.0,0.3) -- (1.0,0.3);
    \node[anchor=west] at (1.05,0.3) {{\scriptsize queued}};
    \draw[deadlinev] (3.0,0.05) -- (3.0,0.55);
    \node[anchor=west] at (3.05,0.3) {{\scriptsize deadline}};
  \end{{scope}}
\end{{tikzpicture}}
"""

# Map "node" string -> style suffix used in the TikZ style names above.
STYLE_SUFFIX = {"polimi-gpu": "A40", "matemagician": "P600"}


def _resolve_label(jid8: str, label_map: dict[str, str], fallback: str) -> str:
    for prefix, name in label_map.items():
        if jid8.startswith(prefix):
            return name
    return fallback


def _parse_offset(spec: str) -> float:
    """Parse a deadline offset string like ``+10m``, ``22m``, ``2h``, ``90s``.

    Returns minutes (float).  Raises SystemExit on parse failure.
    """
    s = spec.strip().lstrip("+")
    if not s:
        raise SystemExit(f"empty deadline offset: {spec!r}")
    unit = s[-1].lower()
    try:
        n = float(s[:-1]) if unit in "smhd" else float(s)
    except ValueError as e:
        raise SystemExit(f"bad deadline offset {spec!r}: {e}") from e
    return {"s": n / 60.0, "m": n, "h": n * 60.0, "d": n * 24 * 60.0}.get(unit, n)


def emit_tikz(
    snap_dir: Path,
    label_map: dict[str, str],
    deadline_overrides: dict[str, float],
) -> str:
    events, jobs, derived, t0 = _load(snap_dir)
    segs = derived["segs"]
    progress = derived["progress"]
    submit_ts: dict[str, datetime] = derived["submit_ts"]

    def to_min(t: datetime) -> float:
        return (t - t0).total_seconds() / 60.0

    # Sort jobs by first dispatch (rows in chronological order, matches PNG).
    job_first_ts: dict[str, datetime] = {}
    for ev in events:
        if ev["kind"] == "dispatch" and "jid" in ev:
            job_first_ts.setdefault(ev["jid"], ev["ts"])
    sorted_jobs = sorted(jobs, key=lambda j: job_first_ts.get(j["id"][:8], t0))

    # Numerical fallback labels: J1..JN by created_at.
    by_created = sorted(jobs, key=lambda j: _parse_iso(j["created_at"]))
    fallback_name = {j["id"][:8]: f"J{i + 1}" for i, j in enumerate(by_created)}

    # Compute x range — only over the jobs actually in jobs.json.  api.log
    # may carry events from later scenario runs (the same file is appended
    # across runs); their segments would otherwise stretch x_max far past
    # the captured snapshot's actual end.
    snapshot_jids = {j["id"][:8] for j in jobs}
    seg_end_max = max(
        (to_min(s["end"]) for jid, sl in segs.items() if jid in snapshot_jids for s in sl),
        default=10.0,
    )
    # Resolve per-job deadline x (in minutes since t0).  Priority order:
    #   1. CLI --deadline override: submit_proxy + offset_minutes
    #   2. jobs.json deadline field (often unreliable in fixture snapshots)
    # The submit proxy is the job's first dispatch in api.log — this is
    # within seconds of real submission and unlike jobs.json's created_at
    # it does not get clobbered by fixture replays.
    job_deadline_x: dict[str, float] = {}
    for j in sorted_jobs:
        jid = j["id"][:8]
        override_min = None
        for prefix, off in deadline_overrides.items():
            if jid.startswith(prefix):
                override_min = off
                break
        # Anchor the deadline override on the *real* submit time from api.log
        # if available, else fall back to first dispatch.
        anchor = submit_ts.get(jid) or job_first_ts.get(jid)
        if override_min is not None and anchor is not None:
            job_deadline_x[jid] = to_min(anchor) + override_min
        elif j.get("created_at") and j.get("deadline"):
            job_deadline_x[jid] = to_min(_parse_iso(j["deadline"]))
    dl_visible = [d for d in job_deadline_x.values() if 0 <= d <= seg_end_max + 5]
    x_max = max(seg_end_max + 4.0, *(dl_visible or [0.0]))

    # Each row is 1.4 tall (so 2-GPU bars at ±0.7 don't overlap neighbours).
    row_gap = 1.4
    rows: list[tuple[str, float, dict]] = []
    for i, j in enumerate(sorted_jobs):
        jid = j["id"][:8]
        y = round(1.0 + i * row_gap, 2)
        rows.append((jid, y, j))

    # Auto-scale x so the picture is roughly 14 cm wide before resizebox.
    xscale = max(0.18, min(0.55, 14.0 / max(x_max, 1.0)))

    lines: list[str] = []
    lines.append(PREAMBLE.format(snap=snap_dir.name, xscale=f"{xscale:.3f}"))

    # Time axis.
    axis_max = x_max + 0.5
    if x_max <= 15:
        tick_step = 2
    elif x_max <= 30:
        tick_step = 4
    elif x_max <= 60:
        tick_step = 5
    else:
        tick_step = 10
    ticks = list(range(0, int(x_max) + 1, tick_step))
    lines.append(f"  \\draw[->] (0,0) -- ({axis_max:.2f},0);\n")
    for t in ticks:
        lines.append(f"  \\draw ({t},0) -- ({t},-0.10) node[below] {{{t}}};\n")
    lines.append(f"  \\node[anchor=west] at ({axis_max + 0.1:.2f},0) {{time [min]}};\n\n")

    # Row labels + bars.
    top_y = 0.0
    for jid, y, j in rows:
        top_y = max(top_y, y + 0.9)
        label = _resolve_label(jid, label_map, fallback_name[jid])
        lines.append(f"  % ---- {label} ({jid}, p={j['priority']} ep={j['epochs_total']})\n")
        lines.append(f"  \\node[anchor=east] at (-0.2,{y}) {{\\textbf{{{label}}}}};\n")

        # Queued segment: from real submit time (api.log first appearance)
        # to first dispatch.  Falls back to jobs.json created_at if api.log
        # mention is missing.
        first_disp = job_first_ts.get(jid)
        submit = submit_ts.get(jid)
        if submit is None and j.get("created_at"):
            submit = _parse_iso(j["created_at"])
        if first_disp is not None and submit is not None:
            q_start = max(0.0, to_min(submit))
            q_end = to_min(first_disp)
            if q_end - q_start > 0.05:
                lines.append(
                    f"  \\draw[queued] ({q_start:.2f},{y}) -- ({q_end:.2f},{y});\n"
                )

        # Bars for each segment.
        for seg in segs.get(jid, []):
            start = to_min(seg["start"])
            end = max(to_min(seg["end"]), start + 0.05)  # avoid zero-width
            n_gpu = sum(seg["gpus"].values())
            half_h = 0.22 if n_gpu == 1 else 0.70
            node = seg["node"]
            style = STYLE_SUFFIX.get(node, "A40")
            lines.append(
                f"  \\draw[node{style}] ({start:.2f},{y - half_h:.2f}) "
                f"rectangle ({end:.2f},{y + half_h:.2f});\n"
            )
            if seg["profile"]:
                lines.append(
                    f"    \\draw[profhatch{style[0]}] ({start:.2f},{y - half_h:.2f}) "
                    f"rectangle ({end:.2f},{y + half_h:.2f});\n"
                )
            if n_gpu == 2:
                mid = (start + end) / 2
                lines.append(
                    f"  \\node[font=\\tiny, anchor=center] at "
                    f"({mid:.2f},{y + half_h + 0.15:.2f}) {{$\\times 2$}};\n"
                )

        # Per-job deadline: short purple tick on the row if in-window.
        # If the deadline is off to the right we instead append a violet
        # ``d $\to$ +Nh'' suffix to the terminal-status marker so it
        # cannot collide with anything.
        dx = job_deadline_x.get(jid)
        dl_suffix = ""
        if dx is not None:
            if 0 <= dx <= x_max:
                lines.append(
                    f"  \\draw[deadlinev] ({dx:.2f},{y - 0.45:.2f}) -- "
                    f"({dx:.2f},{y + 0.45:.2f});\n"
                )
            elif dx > x_max:
                if dx >= 60:
                    off_txt = f"$+${dx / 60:.0f}\\,h"
                else:
                    off_txt = f"$+${dx:.0f}\\,m"
                dl_suffix = (
                    "\\ \\textcolor{violet!70!black}{d\\,$\\to$\\,"
                    + off_txt + "}"
                )

        # Terminal-status marker (with optional deadline-far suffix) next to last bar.
        status = j.get("status", "")
        if status in ("SUCCEEDED", "FAILED"):
            last_end = max((to_min(s["end"]) for s in segs.get(jid, [])), default=0.0)
            prog = progress.get(jid)
            done = prog[0] if prog else j["epochs_total"]
            label_txt = "SUCC." if status == "SUCCEEDED" else "FAIL"
            color = "green!45!black" if status == "SUCCEEDED" else "red!70!black"
            lines.append(
                f"  \\node[anchor=west, font=\\tiny, text={color}] "
                f"at ({last_end + 0.2:.2f},{y}) "
                f"{{{label_txt} {done}/{j['epochs_total']}{dl_suffix}}};\n"
            )
        elif dl_suffix:
            # No terminal marker (e.g. job still running) — emit a standalone
            # off-chart deadline annotation at the right edge.
            last_end = max((to_min(s["end"]) for s in segs.get(jid, [])), default=0.0)
            lines.append(
                f"  \\node[anchor=west, font=\\tiny] "
                f"at ({last_end + 0.2:.2f},{y}) {{{dl_suffix.lstrip()}}};\n"
            )

        lines.append("\n")

    legend_y1 = -1.5
    legend_y2 = -2.6
    lines.append(POSTAMBLE.format(legend_y1=legend_y1, legend_y2=legend_y2))

    return "".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("snap_dir", type=Path)
    p.add_argument("out_tex", type=Path)
    p.add_argument(
        "--label",
        action="append",
        default=[],
        metavar="JID=NAME",
        help="Map a job-id prefix to a display name (e.g. --label af68=PIN-A). "
             "May be passed multiple times.",
    )
    p.add_argument(
        "--deadline",
        action="append",
        default=[],
        metavar="JID=OFFSET",
        help="Override the per-job deadline offset from first dispatch "
             "(e.g. --deadline 022e=+10m or --deadline a4bc=22m). Useful "
             "when jobs.json carries placeholder deadlines.  Units: "
             "s/m/h/d (default minutes).  May be passed multiple times.",
    )
    return p.parse_args(argv)


def main(argv: list[str]) -> None:
    args = parse_args(argv)
    label_map: dict[str, str] = {}
    for spec in args.label:
        if "=" not in spec:
            raise SystemExit(f"Bad --label spec (need JID=NAME): {spec!r}")
        k, v = spec.split("=", 1)
        label_map[k] = v
    deadline_overrides: dict[str, float] = {}
    for spec in args.deadline:
        if "=" not in spec:
            raise SystemExit(f"Bad --deadline spec (need JID=OFFSET): {spec!r}")
        k, v = spec.split("=", 1)
        deadline_overrides[k] = _parse_offset(v)
    tex = emit_tikz(args.snap_dir, label_map, deadline_overrides)
    args.out_tex.write_text(tex)
    print(f"Wrote {args.out_tex} ({len(tex)} bytes)")


if __name__ == "__main__":
    main(sys.argv[1:])
